### ISSUE TITLE
Why .gitignore ignores "settings/local.py"

### ISSUE THREAD

**Issue by nielsonsantana** [xenith/django-base-template#30]
Whats the motivations to ignore `*/settings/local.py` in .gitignore if in `settings/__init__.py`, `local.py` are imported?

**Comment by xenith** [comment]
Some people subscribe to the idea that local and system-specific settings (database URIs, passwords, SECRET_KEYs, api keys, etc) should never be added to version control, and you should have some other method of deploying the local.py file to your servers. I agree with this idea, especially since there are so many instances of projects accidentally adding AWS keys to their repos on GitHub which are then stolen. The reason it throws an error is just to remind you to create the file.

It is easy enough to `git add -f` or remove the line from .gitignore if you disagree with this method. If you don't want a local settings file at all, you just need to remove the exception from `settings/__init__.py`.

**Comment by nielsonsantana** [comment]
Ok. Thanks xenith. I agreen with you about not put sensitive informations on version control. 
Currently use a approach with environment settings( using python-decouple) and the settings inside a `.env` out of version control. I think that this may be a good practice to be added to django-base-template.
