### ISSUE TITLE
DEBU = False mode getting server error after includeing my ip in allowed_hosts[] 

### ISSUE THREAD

**Issue by alteralgo** [xenith/django-base-template#32]
Hi,
In production server, i set DEV=False and debug=False than my IP added to allowed_hosts. but its getting server error 500. Now how can i fix the issue.whats wrong with my settings , But in development mode everything works fine

**Comment by jangeador** [comment]
allowed_hosts refers to the name being used to access. Are you using http://your_ip to access or http://something_else . if it is something_else that is what should go in allowed_hosts.

**Comment by xenith** [comment]
allowed_hosts matches whatever is in the incoming HTTP Host: header (the base URL from the address bar in your browser, normally). This setting is disabled when running DEBUG=True, which is why it works in development. Please see: https://docs.djangoproject.com/en/1.8/ref/settings/#allowed-hosts

Closing this ticket. If you're still having problems, feel free to re-open and post additional details.
